import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {Menu} from "../componentes/Menu"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Loja Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu></Menu>
      <main>
        <h1>Página Inicial</h1>
      </main>
    </div>
  );
}
